//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeCuongOnTap.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Authority()
        {
            this.EssayTests = new HashSet<EssayTest>();
            this.MultiChoices = new HashSet<MultiChoice>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTeacher { get; set; }
        public Nullable<int> IdSubject { get; set; }
        public Nullable<int> IdSem { get; set; }
        public Nullable<int> IdGrade { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EssayTest> EssayTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MultiChoice> MultiChoices { get; set; }
    }
}
