//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeCuongOnTap.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EssayTest
    {
        public int Id { get; set; }
        public string Level { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public bool Status { get; set; }
        public string UpdateTime { get; set; }
        public Nullable<int> IdAuth { get; set; }
    
        public virtual Authority Authority { get; set; }
    }
}
